### PR TITLE
Support ext types

### PR DESCRIPTION
**Pull request by tagomoris**
This change make it possible to pass/receive custom objects, which are serialized/deserialized via Extension types of MessagePack.

### CODE REVIEW

**Comment by authorNari** [comment]
Thanks :)

**Comment by tagomoris** [comment]
@authorNari Can I release the new version (0.2.0) for MRI and JRuby?

**Comment by authorNari** [comment]
@tagomoris Yes, please. 👌

**Comment by tagomoris** [comment]
Done > 0.2.0

**Pull request merged**
